### PR TITLE
Use cpu_features to get cpu instruction set extension information

### PR DESCRIPTION
**Pull request by startrekdude**
# Description

Fixes `get_cpu_flags` returning incorrect results for processors without AVX2 by replacing custom code with code based on [cpu_features](https://github.com/google/cpu_features). Correctly identifies supported instruction set extensions on every possible processor.

[cpu_features](https://github.com/google/cpu_features) is licensed under the (compatible) Apache license and also uses CMake as a build system.

# Issue

Addresses #1588 

# Author(s)

Sam Haskins
cpu_features by Google

# Performance impact

- [ ] quality
- [ ] memory
- [x] speed
- [ ] 8 bit
- [ ] 10 bit
- [ ] N/A

# Test set
- [ ] obj-1-fast can be found [here](https://media.xiph.org/video/derf/objective-1-fast.tar.gz)
- [ ] other
- [x] N/A

# Merge method
- [x] Allow the maintainer to squash and merge when PR is ready to create a 1-commit to the master branch. The maintainer will be able to fix typos / combine commit messages to create a more readable 1-commit message or use whatever is stated in the 'Description' section
- [ ] I will clean up my commits and the maintainer shall use 'rebase and merge' to the master branch

### CODE REVIEW

**Comment by 1480c1** [comment]
Can you either copy the PIC related stuff from `cpu_features`'s cmake to our main cmake and replace the `set(CMAKE_POSITION_INDEPENDENT_CODE ON)` line or alternativly set `set(CMAKE_POSITION_INDEPENDENT_CODE ON)
` inside `cpu_features`?

**Comment by startrekdude** [comment]
I fixed the PIC issue and the cppcheck failure:
```
Checking /home/runner/work/SVT-AV1/SVT-AV1/Source/Lib/Common/Codec/common_dsp_rtcd.c: ARCH_X86_64=1;_FORTIFY_SOURCE=2...
Error: error: #error "Including cpuinfo_x86.h from a non-x86 target." (preprocessorErrorDirective)
```
is a false positive most likely due to cppcheck not #define-ing the architecture in quite the same way as a real compiler.

Not sure why it's failing every time it needs to go inside FFmpeg, if anyone could shine some light on that it would be very helpful.

Thanks @1480c1 for the -fPIC hint!

**Comment by ePirat** [comment]
Are you sure this is fine, License wise? It seems the cpu_features is licensed as Apache-2.0 License so I am not sure you can just copy their code to SVT-AV1.

**Comment by startrekdude** [comment]
That last commit fixed the rest of the build checks except for the cppcheck false positive I mentioned earlier and the ones that are failing for the other open pull requests too.

Regarding licensing: while I'm not an expert, I believe it should be possible to include cpu_features as a dependency as the [Apache 2.0 License](https://choosealicense.com/licenses/apache-2.0/) allows linking from other code, assuming attribution is given.

**Comment by ePirat** [comment]
The issue is less what the Apache license allows but the fact that integrating this into SVT-AV1 will make part of it licensed under the Apache license, leading to issues like the incompatibility of the Apache 2.0 license with the GPL 2 (https://opensource.stackexchange.com/questions/5664/linking-from-lgpl-2-1-software-to-apache-2-0-library)

**Comment by hassount** [comment]
@startrekdude thank you for the contribution. From previous legal discussions, the Apache 2.0 license does create a conflict license especially when linking libraries to ffmpeg, so we would not be able to use the Apache 2.0 licensed code. Would you be able to use the current functions to derive the information needed ?

**Comment by startrekdude** [comment]
I can do it with the BSD-licensed [cpuinfo](https://github.com/pytorch/cpuinfo). Would that be acceptable?

**Comment by hassount** [comment]
> I can do it with the BSD-licensed [cpuinfo](https://github.com/pytorch/cpuinfo). Would that be acceptable?

that should be ok, but let me get a legal advise just to make sure

**Comment by hassount** [comment]
> > I can do it with the BSD-licensed [cpuinfo](https://github.com/pytorch/cpuinfo). Would that be acceptable?
> 
> that should be ok, but let me get a legal advise just to make sure

Legal has approved the use of the BSD cpuinfo, you can go ahead

**Comment by startrekdude** [comment]
Alright, thanks! Will do.

**Pull request closed without merging**
