### PR TITLE
avx2: eb_av1_haar_ac_sad_8x8_uint8_input_avx2, fix unaligned mov for transpose_32bit_8x8_avx2

### PR DESCRIPTION
**Pull request by xuguangxin**
# Description
steps to reproduce:
1. build with debug. "mkdir build && cd build && cmake ..  -DCMAKE_BUILD_TYPE=Debug && make install"
2. run "SvtAv1EncApp -lp 4 -lad 0 -q 20 -n 3 -intra-period 119 -i ~/bits/SVT/vidyo_720p.y4m -b two_passes.ivf --passes 2 --preset 3"
3. you will see a core dump.

details:
We need declare the output as 32 bytes aligned since transpose_32bit_8x8_avx2 will unref it as __m256i*

# Issue

# Author(s)

# Performance impact

- [ ] quality
- [ ] memory
- [ ] speed
- [ ] 8 bit
- [ ] 10 bit
- [x] N/A

# Test set
- [ ] obj-1-fast can be found [here](https://media.xiph.org/video/derf/objective-1-fast.tar.gz)
- [ ] other
- [x] N/A

# Merge method
- [ ] Allow the maintainer to squash and merge when PR is ready to create a 1-commit to the master branch. The maintainer will be able to fix typos / combine commit messages to create a more readable 1-commit message or use whatever is stated in the 'Description' section
- [x] I will clean up my commits and the maintainer shall use 'rebase and merge' to the master branch

### CODE REVIEW

**Comment by tszumski** [comment]
LGTM

**Comment by hassount** [comment]
we might need to check Valgrind on this while we figure out why Travis isn't working

**Comment by xuguangxin** [comment]
> we might need to check Valgrind on this while we figure out why Travis isn't working

Valgrind may not catch this. It's a runtime issue, depends on the stack allocation,

**Comment by ccccheung** [comment]
Tested 6 8 bit clips and 6 10 bit clips with a mix of resolutions
This PR is lossless and does indeed fix the core dump mentioned in the issue
 
  | Speed Deviation  | BD-Rate   Deviation | Memory Deviation
-- | -- | -- | --
M0 - 8bit| 0.01% | 0.00% | -0.02%
M4 - 8bit| 0.18% | 0.00% | 0.05%
M8 - 8bit| 0.66% | 0.00% | 0.01%
M0 - 10bit| 0.09% | 0.00% | 0.00%
M4 - 10bit| 0.18% | 0.00% | 0.00%
M8 - 10bit| -0.14% | 0.00% | -0.01%

**Pull request merged**
