### PR TITLE
Make build possible with -mmacosx-version-min < 10.12

### PR DESCRIPTION
**Pull request by palexander-14**
# Description
Added preprocessor conditions for build the code on macOS for deployment on macOS older than 10.12

# Issue

# Author(s)
Polishchuk Alexander

# Performance impact

- [ ] quality
- [ ] memory
- [ ] speed
- [ ] 8 bit
- [ ] 10 bit
- [x] N/A

# Test set
- [ ] obj-1-fast can be found [here](https://media.xiph.org/video/derf/objective-1-fast.tar.gz)
- [ ] other
- [x] N/A

# Merge method
- [x] Allow the maintainer to squash and merge when PR is ready to create a 1-commit to the master branch. The maintainer will be able to fix typos / combine commit messages to create a more readable 1-commit message or use whatever is stated in the 'Description' section
- [ ] I will clean up my commits and the maintainer shall use 'rebase and merge' to the master branch

### CODE REVIEW

**Comment by palexander-14** [comment]
A bit more info.
I have to create binaries for macOS with -mmacosx-version-min=10.9, and there is nothing I can do with it. I suppose a can be not alone with this problem.
Building with the specified compiler flag gave the following error:
`Source/Lib/Common/Codec/EbTime.c:44:5: error: 'clock_gettime' is only available on macOS 10.12 or newer`

Proposed patch solves this problem.

**Comment by hassount** [comment]
@palexander-14  thank you for the PR, Can you please make sure, you and / or the entity owning the work can sign the ICLA/ ECLA? https://github.com/AOMediaCodec/SVT-AV1#contributor-agreement

Also can you please rebase to make sure that the tests have passed ?

**Comment by hassount** [comment]
@palexander-14 

Thank you for rebasing, please let me know when the CLA is signed to merge this PR.

**Comment by palexander-14** [comment]
ICLA has been signed

**Pull request merged**
