### PR TITLE
Cleanup rename eb_ to  svt_ cleanup 8,16bit names

### PR DESCRIPTION
**Pull request by spawlows**
# Description
Rename kernels names eb_ to svt_, some cleanup 8 and 16 bit kernel names, and add small git ignore rules.

# Issue

# Author(s)
@spawlows 

# Performance impact

- [ ] quality
- [ ] memory
- [ ] speed
- [ ] 8 bit
- [ ] 10 bit
- [x] N/A

# Test set
- [ ] obj-1-fast can be found [here](https://media.xiph.org/video/derf/objective-1-fast.tar.gz)
- [ ] other
- [x] N/A

# Merge method
- [x] Allow the maintainer to squash and merge when PR is ready to create a 1-commit to the master branch. The maintainer will be able to fix typos / combine commit messages to create a more readable 1-commit message or use whatever is stated in the 'Description' section
- [ ] I will clean up my commits and the maintainer shall use 'rebase and merge' to the master branch

### CODE REVIEW

**Review by ttrigui — APPROVED** [review]

**Comment by paulsgh** [comment]
Tested a mix of clips comprised of different resolutions and bit depths.
This PR is lossless.

| | Speed Deviation  | BD-Rate   Deviation | Memory Deviation
-- | -- | -- | --
M0 - 8bit - 2pass| 0.67% | 0.00% | -0.01%
M0 - 10bit - 2pass| 0.42% | 0.00% | 0.00%
M0 - 8bit - 1pass| 0.59% | 0.00% | 0.02%
M4 - 8bit - 1pass| 0.90% | 0.00% | 0.00%
M8 - 8bit - 1pass| 0.43% | 0.00% | 0.00%
M0 - 10bit - 1pass| 0.51% | 0.00% | 0.02%
M4 - 10bit - 1pass| 0.81% | 0.00% | 0.01%
M8 - 10bit - 1pass| 1.07% | 0.00% | 0.01%

**Review by OmranAbdelkafi — APPROVED** [review]

**Comment by spawlows** [comment]
Conflicts resolved.

**Comment by spawlows** [comment]
Hi,

On this breanch https://github.com/spawlows/SVT-AV1/tree/cleanup-prefix-svt-cleanup-8-16bit-names-mege-with-chkngit-pr03_1

I resolved all confilts with PR  #1526

**Comment by spawlows** [comment]
Conflicts resolved.

**Pull request merged**
