### PR TITLE
CMake: Add option to compile using C code only

### PR DESCRIPTION
**Pull request by 1480c1**
# Description

Allows for a way to build a C only executable even on x86* cpus

Accessible through cmake directly using

```bash
cmake -DCOMPILE_C_ONLY=On
```

or alternativly through ccmake or through the build scripts

for windows:

```bat
.\Build\windows\build.bat c-only
```

for *nix systems

```bash
./Build/linux/build.sh --c-only
````

# Issue

# Author(s)
@1480c1 

# Performance impact

- [ ] quality
- [ ] memory
- [ ] speed
- [ ] 8 bit
- [ ] 10 bit
- [x] N/A

# Test set
- [ ] obj-1-fast can be found [here](https://media.xiph.org/video/derf/objective-1-fast.tar.gz)
- [ ] other
- [x] N/A

# Merge method
- [x] Allow the maintainer to squash and merge when PR is ready to create a 1-commit to the master branch. The maintainer will be able to fix typos / combine commit messages to create a more readable 1-commit message or use whatever is stated in the 'Description' section
- [ ] I will clean up my commits and the maintainer shall use 'rebase and merge' to the master branch

### CODE REVIEW

**Comment by 1480c1** [comment]
Seems msvc is being a bit annoying since it's making the asm files inherit the defines even though they are supposed to be C and C++ only, going to test more in another branch

**Comment by hassount** [comment]
@1480c1 thank you for the PR, can we document in the commit message / the PR how to use this option. Potentially adding an option in the build.sh / build.bat script as an example.

**Comment by 1480c1** [comment]
Updated the commit message along with adding the options, I have only tested the build.sh so far, haven't tried the build.bat

**Review by ttrigui — APPROVED** [review]

**Comment by paulsgh** [comment]
Tested a mix of clips comprised of different resolutions and bit depths.
This PR is lossless.

| | Speed Deviation  | BD-Rate   Deviation | Memory Deviation
-- | -- | -- | --
M0 - 8bit - 2pass| 0.10% | 0.00% | -0.01%
M0 - 10bit - 2pass| 0.03% | 0.00% | 0.00%
M0 - 8bit - 1pass| 0.03% | 0.00% | 0.00%
M4 - 8bit - 1pass| 0.28% | 0.00% | 0.03%
M8 - 8bit - 1pass| -0.75% | 0.00% | 0.02%
M0 - 10bit - 1pass| -0.03% | 0.00% | 0.00%
M4 - 10bit - 1pass| 0.21% | 0.00% | 0.01%
M8 - 10bit - 1pass| 0.81% | 0.00% | -0.01%

**Pull request merged**
