### PR TITLE
CI: Attempt to compile macOS Arm64 target for Apple Silicon

### PR DESCRIPTION
**Pull request by EwoutH**
Draft PR to figure out building universal/fat binaries.

Currently a lot of [these errors](https://github.com/EwoutH/SVT-AV1/runs/1489231639?check_suite_focus=true#step:6:223) pop up when compiling with CMake 3.19.1 and Xcode 12.2 using `-DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"`:

- `error: this header is for x86 only`
- `error: invalid output constraint '=a' in asm`
- `error: redefinition of 'cpuinfo_isa' with a different type: 'struct cpuinfo_x86_isa' vs 'struct cpuinfo_arm_isa'`
- `error: calling 'cpuinfo_x86_detect_isa' with incomplete return type 'struct cpuinfo_x86_isa'`

@1480c1 Do you want to give it a shot?

Probably first building for arm64 and then combining it with x86_64 into a fat binary could also be a solid strategy.

Part of #1569.

(all other workflows other than macOS are disabled for performance reasons.

### CODE REVIEW

**Comment by 1480c1** [comment]
I am assuming the issue you are seeing is due to the removal of arm related code from the cpuinfo dependency

**Comment by EwoutH** [comment]
Right, this looks like the same issue why [Travis CI is failing](https://travis-ci.com/github/EwoutH/SVT-AV1/jobs/452929271#L587). I rebased on the last commit before that change, let's see what happens.

**Comment by EwoutH** [comment]
https://github.com/EwoutH/SVT-AV1/runs/1489487322?check_suite_focus=true#step:6:1632
```
clang: error: no such file or directory: '/Users/runner/work/SVT-AV1/SVT-AV1/Bin/Release/Release/libSvtAv1Enc.a'
Command Ld failed with a nonzero exit code
```
Looks like the file/directory structure changed, since there are no other errors or failures. The `Release/Release` part is a bit strange. I'm going to take a fresh look in the morning.

**Comment by EwoutH** [comment]
Unix build now works: https://github.com/EwoutH/SVT-AV1/runs/1489584934?check_suite_focus=true

**Comment by EwoutH** [comment]
Something went wrong with rebasing, will open a new PR

**Pull request closed without merging**
