### PR TITLE
Preset tuning

### PR DESCRIPTION
**Pull request by okhlif**
# Description

Preset tuning for better tradeoffs

# Issue

# Author(s)
@PhoenixWorth 
@Arhuan 

# Performance impact

- [x] quality
- [ ] memory
- [x] speed
- [x] 8 bit
- [x] 10 bit
- [ ] N/A

# Test set
- [ ] obj-1-fast can be found [here](https://media.xiph.org/video/derf/objective-1-fast.tar.gz)
- [x] other
- [ ] N/A

M7 
PSNR Y | PSNR  U | PSNR  V | Speed Dev | memory   reduction
-- | -- | -- | -- | --
2.01% | 1.60% | 1.98% | 28% | 0%

# Merge method
- [x] Allow the maintainer to squash and merge when PR is ready to create a 1-commit to the master branch. The maintainer will be able to fix typos / combine commit messages to create a more readable 1-commit message or use whatever is stated in the 'Description' section
- [ ] I will clean up my commits and the maintainer shall use 'rebase and merge' to the master branch

### CODE REVIEW

**Comment by hassount** [comment]
@okhlif rebasing should address the patches CI failed use cases.

**Comment by okhlif** [comment]
> @okhlif rebasing should address the patches CI failed use cases.

Thanks Just rebased the branch

**Comment by hassount** [comment]
@okhlif I believe that it's best to rebase this to get #1598 in

**Comment by okhlif** [comment]
> @okhlif I believe that it's best to rebase this to get #1598 in

Just did and added a fix for the unit tests.

**Pull request merged**
