### PR TITLE
EncApp: Refact, split encode function to smaller functions.

### PR DESCRIPTION
**Pull request by xuguangxin**
# Description
split encode function to smaller functions to more readable samller functions. 

Tested command:

- SvtAv1EncApp -lp 4 -lad 0 -q 20  -n 3 -intra-period 119 -i ~/bits/SVT/172x144.y4m -i ~/bits/SVT/172x144.y4m -b two_passes.ivf --passes 2 --preset 3 -tttt
- SvtAv1EncApp -lp 4 -lad 0 -q 20  -n 3 -intra-period 119 -i ~/bits/SVT/172x144.y4m -i ~/bits/SVT/172x144.y4m -b two_passes.ivf --passes 2 --preset 3
- SvtAv1EncApp -nch 2 -c 1.cfg 2.cfg

# Issue

# Author(s)
Guangxin.Xu@intel.com

# Performance impact

- [ ] quality
- [ ] memory
- [ ] speed
- [ ] 8 bit
- [ ] 10 bit
- [x] N/A

# Test set
- [ ] obj-1-fast can be found [here](https://media.xiph.org/video/derf/objective-1-fast.tar.gz)
- [ ] other
- [x] N/A

# Merge method
- [ ] Allow the maintainer to squash and merge when PR is ready to create a 1-commit to the master branch. The maintainer will be able to fix typos / combine commit messages to create a more readable 1-commit message or use whatever is stated in the 'Description' section
- [x] I will clean up my commits and the maintainer shall use 'rebase and merge' to the master branch

### CODE REVIEW

**Comment by 1480c1** [comment]
@xuguangxin can you check the msvc debug build? It seems it has an error

```c
D:\a\SVT-AV1\SVT-AV1\test\e2e_test\ConfigEncoder.cc(27,26): error C2664: 'EbConfig *eb_config_ctor(EncodePass)': cannot convert argument 1 from 'EbConfig *' to 'EncodePass' [D:\a\SVT-AV1\SVT-AV1\Build\test\e2e_test\SvtAv1E2ETests.vcxproj]
D:\a\SVT-AV1\SVT-AV1\test\e2e_test\ConfigEncoder.cc(27,20): message : There is no context in which this conversion is possible [D:\a\SVT-AV1\SVT-AV1\Build\test\e2e_test\SvtAv1E2ETests.vcxproj]
D:\a\SVT-AV1\SVT-AV1\Source\App\EncApp\EbAppConfig.c(1408,12): message : see declaration of 'eb_config_ctor' [D:\a\SVT-AV1\SVT-AV1\Build\test\e2e_test\SvtAv1E2ETests.vcxproj]
```

**Comment by xuguangxin** [comment]
@1480c1 ， done, thanks for point out

**Comment by hassount** [comment]
@xuguangxin can you please rebase ?

**Comment by ccccheung** [comment]
Tested with objective 1 fast
This PR is lossless
 
  | Speed Deviation  | BD-Rate   Deviation | Memory Deviation
-- | -- | -- | --
M0 - 8bit - 1 pass| 0.14% | 0.00% | -0.02%
M4 - 8bit- 1 pass| 0.90% | 0.00% | 0.00%
M8 - 8bit- 1 pass| 0.81% | 0.00% | 0.00%
M0 - 10bit- 1 pass| 1.01% | 0.00% | -0.02%
M4 - 10bit - 1 pass| 0.72% | 0.00% | 0.01%
M8 - 10bit- 1 pass| 0.35% | 0.00% | -0.01%
M0 - 8bit - 2 pass| 1.19% | 0.00% | -0.15%
M0 - 10bit - 2 pass| 1.09% | 0.00% | 0.03%

**Review by OmranAbdelkafi — APPROVED** [review]

**Comment by xuguangxin** [comment]
ccccheung , OmranAbdelkafi  thanks for test and review.
@hassount  rebased, but mac ci has some configuration problem. It's not introduced by this patchset.

thanks

**Comment by 1480c1** [comment]
@xuguangxin can you either rebase or somehow force a rebuild? I believe the macOS issue is fixed

**Comment by xuguangxin** [comment]
@1480c1 thanks for the fix, rebased.

**Pull request merged**
