### PR TITLE
Cleanup, unification of function names add svt_ prefix

### PR DESCRIPTION
**Pull request by spawlows**
# Description
Cleanup, unification of function names add svt_ prefix
Fix small issue when run VS Debug.
Fix compilation error for AVX512

# Issue

# Author(s)
@spawlows 

# Performance impact

- [ ] quality
- [ ] memory
- [ ] speed
- [ ] 8 bit
- [ ] 10 bit
- [x] N/A

# Test set
- [ ] obj-1-fast can be found [here](https://media.xiph.org/video/derf/objective-1-fast.tar.gz)
- [ ] other
- [x] N/A

# Merge method
- [x] Allow the maintainer to squash and merge when PR is ready to create a 1-commit to the master branch. The maintainer will be able to fix typos / combine commit messages to create a more readable 1-commit message or use whatever is stated in the 'Description' section
- [ ] I will clean up my commits and the maintainer shall use 'rebase and merge' to the master branch

### CODE REVIEW

**Comment by ccccheung** [comment]
Tested with objective 1 8bit/10 bit
This PR is lossless
  | Speed Deviation  | BD-Rate   Deviation | Memory Deviation
-- | -- | -- | --
M0 - 8bit| 2.31% | 0.00% | -0.01%
M4 - 8bit| 2.15% | 0.00% | -0.02%
M8 - 8bit| 2.21% | 0.00% | -0.02%
M0 - 10bit| 1.72% | 0.00% | -0.02%
M4 - 10bit| 1.57% | 0.00% | -0.01%
M8 - 10bit| 0.47% | 0.00% | -0.01%
M0 - 8bit - 2pass| 2.35% | 0.00% | -0.02%
M0 - 10bit - 2pass| 1.82% | 0.00% | -0.02%

**Review by OmranAbdelkafi — APPROVED** [review]

**Comment by hassount** [comment]
> Tested with objective 1 8bit/10 bit
> This PR is lossless
> 
>  	Speed Deviation	BD-Rate Deviation	Memory Deviation
> M0 - 8bit	2.31%	0.00%	-0.01%
> M4 - 8bit	2.15%	0.00%	-0.02%
> M8 - 8bit	2.21%	0.00%	-0.02%
> M0 - 10bit	1.72%	0.00%	-0.02%
> M4 - 10bit	1.57%	0.00%	-0.01%
> M8 - 10bit	0.47%	0.00%	-0.01%
> M0 - 8bit - 2pass	2.35%	0.00%	-0.02%
> M0 - 10bit - 2pass	1.82%	0.00%	-0.02%

@ccccheung ran on the same machine ?

**Comment by ccccheung** [comment]
> > Tested with objective 1 8bit/10 bit
> > This PR is lossless
> >  	Speed Deviation	BD-Rate Deviation	Memory Deviation
> > M0 - 8bit	2.31%	0.00%	-0.01%
> > M4 - 8bit	2.15%	0.00%	-0.02%
> > M8 - 8bit	2.21%	0.00%	-0.02%
> > M0 - 10bit	1.72%	0.00%	-0.02%
> > M4 - 10bit	1.57%	0.00%	-0.01%
> > M8 - 10bit	0.47%	0.00%	-0.01%
> > M0 - 8bit - 2pass	2.35%	0.00%	-0.02%
> > M0 - 10bit - 2pass	1.82%	0.00%	-0.02%
> 
> @ccccheung ran on the same machine ?

Yes. they were run on the same machine

**Review by ttrigui — APPROVED** [review]

**Comment by spawlows** [comment]
Conflicts resolved.

**Comment by ttrigui** [comment]
can we please merge this PR ?

**Pull request merged**
