### PR TITLE
API document fix

### PR DESCRIPTION
**Pull request by tianjunwork**
Signed-off-by: Jun Tian <jun.tian@intel.com>

### CODE REVIEW

**Comment by tianjunwork** [comment]
not used interface:
 EbBool in_loop_me_flag;
	
missing in user guide:
#define SCENE_CHANGE_DETECTION_TOKEN "-scd"
#define SUPERRES_MODE_INPUT "-superres-mode"
#define SUPERRES_DENOM "-superres-denom"
#define SUPERRES_KF_DENOM "-superres-kf-denom"
#define SUPERRES_QTHRES "-superres-qthres"
		
missing comment in EbSvtAv1Enc.h:
    EbBool  enable_altrefs;
    uint8_t altref_strength;
    uint8_t altref_nframes;
    EbBool  enable_overlays;

    // super-resolution parameters
    uint8_t superres_mode;
    uint8_t superres_denom;
    uint8_t superres_kf_denom;
    uint8_t superres_qthres;

    uint32_t sq_weight;

    uint64_t md_stage_1_cand_prune_th;
    uint64_t md_stage_1_class_prune_th;
    uint64_t md_stage_2_3_cand_prune_th;
    uint64_t md_stage_2_3_class_prune_th;

**Comment by adaria** [comment]
Hi @tianjunwork, is this still a Draft/WIP or is it ready to go? Thanks!

**Comment by tianjunwork** [comment]
> Hi @tianjunwork, is this still a Draft/WIP or is it ready to go? Thanks!

Hi @adaria , it is still in progress. Some of the features need the author to comment on them. I didn't contact them yet. How soon do you need this PR to be done? Let me know how I can help.

**Comment by adaria** [comment]
> > Hi @tianjunwork, is this still a Draft/WIP or is it ready to go? Thanks!
> 
> Hi @adaria , it is still in progress. Some of the features need the author to comment on them. I didn't contact them yet. How soon do you need this PR to be done? Let me know how I can help.

Thanks @tianjunwork. I was asked to review the PR when ready, it is not a blocker as far as I know. 
I've authored some of the command line options, I'll have a look if I can help too.

**Comment by zyue128** [comment]
also, is -latency-mode still supported? I can't find it in the doc too.

**Pull request closed without merging**
